permissionset 50300 "RestClientOAuth KFM"
{
    Caption = 'Rest Client OAuth Permissions', Locked = true;
    Assignable = true;
    Permissions = table "Entra App Registration KFM" = X,
tabledata "Entra App Registration KFM" = RIMD,
        table "Entra Certificate KFM" = X,
        tabledata "Entra Certificate KFM" = RIMD,
        table "Entra Secret KFM" = X,
        tabledata "Entra Secret KFM" = RIMD,
        codeunit "Auth. Code Grant Flow KFM" = X,
        codeunit AuthCodeGrantFlowImplKFM = X,
        codeunit ClientCredentialsFlowImplKFM = X,
        codeunit "Client Credentials Flow KFM" = X,
        codeunit DeviceCodeFlowImplKFM = X,
        codeunit "Device Code Flow KFM" = X,
        codeunit "Entra Certificate Mgt KFM" = X,
        codeunit HttpAuthenticationOAuth2ImpKFM = X,
        codeunit "Http Authentication OAuth2 KFM" = X,
        codeunit "Http Client Handler KFM" = X,
        codeunit "Microsoft Entra ID Impl. KFM" = X,
        codeunit "Microsoft Entra ID KFM" = X,
        codeunit OAuthApplicationConfigImplKFM = X,
        codeunit "OAuth Application Config KFM" = X,
        codeunit "OAuth AuthenticationResult KFM" = X,
        codeunit OAuthAuthenticationRsltImplKFM = X,
        codeunit "OAuth Certificate Impl. KFM" = X,
        codeunit "OAuth Certificate KFM" = X,
        codeunit OAuthConfidentialClientImplKFM = X,
        codeunit "OAuth Confidential Client KFM" = X,
        codeunit OAuthPublicClientImplKFM = X,
        codeunit "OAuth Public Client KFM" = X,
        codeunit "Redirect URI Built-in KFM" = X,
        codeunit "Redirect URI None KFM" = X,
        codeunit TimeHelper = X,
        page AuthCodeGrantFlowBuiltinKFM = X,
        page "Device Code Authorization KFM" = X,
        page "Entra App Registr. Card KFM" = X,
        page "Entra App Registr. List KFM" = X,
        page "Entra Certificates KFM" = X,
        page "Entra Secret Subform KFM" = X;
}